// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIaCx2uJoisQD7wDnHmlrcsvEe9ppOt0',
    appId: '1:752512763723:web:e0813556d2f62bfcc28ace',
    messagingSenderId: '752512763723',
    projectId: 'reviveapp-64f08',
    authDomain: 'reviveapp-64f08.firebaseapp.com',
    storageBucket: 'reviveapp-64f08.firebasestorage.app',
    measurementId: 'G-1ERR7RSY1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXKKIvYKWTQ9MK5vkQ7JwOqrBGTi1Quk',
    appId: '1:752512763723:android:e1c0dd119d6b46ecc28ace',
    messagingSenderId: '752512763723',
    projectId: 'reviveapp-64f08',
    storageBucket: 'reviveapp-64f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXNGMi_ne9gtq-TMmbfWd_slSePk_68c',
    appId: '1:752512763723:ios:3a2b84f7e9332a16c28ace',
    messagingSenderId: '752512763723',
    projectId: 'reviveapp-64f08',
    storageBucket: 'reviveapp-64f08.firebasestorage.app',
    iosClientId: '752512763723-aea9d7tbe23vhtr35ghnicfsgbo62kor.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXNGMi_ne9gtq-TMmbfWd_slSePk_68c',
    appId: '1:752512763723:ios:3a2b84f7e9332a16c28ace',
    messagingSenderId: '752512763723',
    projectId: 'reviveapp-64f08',
    storageBucket: 'reviveapp-64f08.firebasestorage.app',
    iosClientId: '752512763723-aea9d7tbe23vhtr35ghnicfsgbo62kor.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSIaCx2uJoisQD7wDnHmlrcsvEe9ppOt0',
    appId: '1:752512763723:web:e4434fa0586a5a81c28ace',
    messagingSenderId: '752512763723',
    projectId: 'reviveapp-64f08',
    authDomain: 'reviveapp-64f08.firebaseapp.com',
    storageBucket: 'reviveapp-64f08.firebasestorage.app',
    measurementId: 'G-CK494SJW8M',
  );
}
